### ISSUE TITLE
哥们  出错了

### ISSUE THREAD

**Issue by Funny-dot** [SQDYY/wx-tencent-im#1]
![image](https://user-images.githubusercontent.com/27287970/53460515-5e0e6900-3a78-11e9-8d72-62b4303c1fa9.png)

**Comment by 100101001** [comment]
{"ActionStatus":"FAIL","ErrorInfo":"Invalid format of To_Account","ErrorCode":90003} sendMsg接口

**Comment by SQDYY** [comment]
你没装express模块啊

**Comment by ScrappedPrincess** [comment]
安装express，http://www.expressjs.com.cn/
