### ISSUE TITLE
sendMsg接口

### ISSUE THREAD

**Issue by 100101001** [SQDYY/wx-tencent-im#4]
{"ActionStatus":"FAIL","ErrorInfo":"Invalid format of To_Account","ErrorCode":90003} sendMsg接口

**Comment by SQDYY** [comment]
To_Account传错了

**Comment by ScrappedPrincess** [comment]
https://cloud.tencent.com/document/product/269/2282

**Comment by ScrappedPrincess** [comment]
完成账户注册和双向添加好友了吗
